<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="LibreOffice 4.1.6.2 (Linux)">
	<META NAME="AUTHOR" CONTENT="Viktor Geiger">
	<META NAME="CREATED" CONTENT="20161210;115136000000000">
	<META NAME="CHANGEDBY" CONTENT="Viktor Geiger">
	<META NAME="CHANGED" CONTENT="20161210;120307000000000">
	<STYLE TYPE="text/css">
	<!--
		@page { margin: 0.79in }
		P { margin-bottom: 0.1in; line-height: 120% }
		A.sdfootnotesym-western { font-family: "Times New Roman", serif; font-size: 11pt }
		A.sdfootnotesym-cjk { font-size: 11pt }
		A.sdfootnotesym-ctl { font-family: "Times New Roman", serif }
	-->
	</STYLE>
</HEAD>
<BODY LANG="de-DE" DIR="LTR">
<DIV TYPE=HEADER>
	<P STYLE="margin-bottom: 0in; line-height: 100%"><IMG SRC="i_1982c8872648c895_html_6217b7b9.jpg" NAME="Image1" ALIGN=LEFT WIDTH=155 HEIGHT=60 BORDER=0>		FH
	Ravensburg-Weingarten</P>
	<P STYLE="margin-bottom: 0.2in; border-top: none; border-bottom: 1.00pt solid #000000; border-left: none; border-right: none; padding-top: 0in; padding-bottom: 0.03in; padding-left: 0in; padding-right: 0in; line-height: 100%">
			Fakultät Elektrotechnik und Informatik</P>
</DIV>
<TABLE WIDTH=640 CELLPADDING=0 CELLSPACING=0>
	<COL WIDTH=638>
	<TR>
		<TD WIDTH=638 HEIGHT=1 BGCOLOR="#5c6971" STYLE="border-top: 1px solid #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
			<FONT COLOR="#ffffff"><FONT SIZE=4 STYLE="font-size: 16pt"><B>G U
			T A C H T E N</B></FONT></FONT></P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%"><BR>
</P>
<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0>
	<COLGROUP>
		<COL WIDTH=72*>
	</COLGROUP>
	<COLGROUP>
		<COL WIDTH=72*>
		<COL WIDTH=49*>
		<COL WIDTH=64*>
	</COLGROUP>
	<TR>
		<TD WIDTH=28% VALIGN=TOP STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2><B>Art
			der wissenschaftlichen Arbeit</B></FONT></P>
		</TD>
		<TD WIDTH=28% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.04in"><BR>
			</P>
		</TD>
		<TD WIDTH=19% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 11pt">${ProjectType}</FONT></P>
		</TD>
		<TD WIDTH=25% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.04in"><BR>
			</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=28% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in; margin-bottom: 0.04in">
			<FONT SIZE=2><B>Thema der Arbeit</B></FONT></P>
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in; margin-bottom: 0.04in">
			<BR><BR>
			</P>
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><BR>
			</P>
		</TD>
		<TD COLSPAN=3 WIDTH=72% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.04in">
			<FONT SIZE=2><B>${ProjectTitle}</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=28% HEIGHT=5 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2><B>Verfasser/in</B></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=72% VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.04in">
			${AuthorLastName}, ${AuthorFirstName} ,
			Matrikelnummer:  ${AuthorMatrNr}</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=28% HEIGHT=5 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2><B>Kurs</B></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=72% VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.04in">
			${course}
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=28% HEIGHT=3 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2><B>Wissenschaftlicher
			Betreuer</B></FONT></P>
		</TD>
		<TD COLSPAN=3 WIDTH=72% VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.04in">
			${SuperVisorLastName}, ${SuperVisorFirstName}</P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0.08in; line-height: 100%"><BR><BR>
</P>
<TABLE WIDTH=642 CELLPADDING=0 CELLSPACING=1>
	<COL WIDTH=342>
	<COL WIDTH=139>
	<COL WIDTH=95>
	<COL WIDTH=59>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=638 BGCOLOR="#5c6971" STYLE="border-top: 1px solid #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.03in; page-break-after: avoid">
				<FONT COLOR="#ffffff"><FONT SIZE=2><B>1. Themenerfassung und
				Strukturierung</B></FONT></FONT></P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=482 HEIGHT=17 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Prüfkriterien des
				Gutachters / Betreuers</B></FONT></P>
			</TD>
			<TD WIDTH=95 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Bewertungstendenz</B></FONT></P>
			</TD>
			<TD WIDTH=59 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>nicht<BR>relevant</B></FONT></P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=482 HEIGHT=7 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.16in; margin-top: 0.04in; page-break-after: avoid">
				<BR>
				</P>
			</TD>
			<TD WIDTH=95 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
			<TD WIDTH=59 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=482 HEIGHT=33 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">klar und eindeutig
					formulierte Problemstellung und Zielsetzung der Arbeit</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=95 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=59 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=482 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">richtige und vollständige
					Erfassung des Themas</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=95 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=59 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=482 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; margin-bottom: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">logische, aussagekräftige
					Gliederung mit einer der Themenstellung angemessenen </FONT>
					</P>
				</UL>
				<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
				    <FONT SIZE=2 STYLE="font-size: 9pt">Tiefe</FONT></P>
			</TD>
			<TD WIDTH=95 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=59 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=482 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">Aktualität und
					Praxisrelevanz der Themenstellung</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=95 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>		
				–		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=59 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=638 HEIGHT=214 VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.04in; margin-bottom: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Bemerkungen</B></FONT><FONT SIZE=2 STYLE="font-size: 9pt">:</FONT></P>
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD WIDTH=342 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Maximale Punktzahl:		20</B></FONT></P>
			</TD>
			<TD COLSPAN=3 WIDTH=295 VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Erreichte
				Punktzahl:	</B></FONT></P>
			</TD>
		</TR>
	</TBODY>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%; page-break-before: always">
<BR>
</P>
<TABLE WIDTH=641 CELLPADDING=0 CELLSPACING=1>
	<COL WIDTH=342>
	<COL WIDTH=141>
	<COL WIDTH=94>
	<COL WIDTH=57>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=637 BGCOLOR="#5c6971" STYLE="border-top: 1px solid #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.03in; page-break-after: avoid">
				<FONT COLOR="#ffffff"><FONT SIZE=2><B>2. Themenbearbeitung</B></FONT></FONT></P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=17 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Prüfkriterien des
				Gutachters / Betreuers</B></FONT></P>
			</TD>
			<TD WIDTH=94 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Bewertungstendenz</B></FONT></P>
			</TD>
			<TD WIDTH=57 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>nicht<BR>relevant</B></FONT></P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=7 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.16in; margin-top: 0.04in; page-break-after: avoid">
				<BR>
				</P>
			</TD>
			<TD WIDTH=94 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
			<TD WIDTH=57 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">sachgerechte
					Begriffsabgrenzung und stringente Anwendung in der
					Themen&shy;bearbeitung, korrekte Verwendung der fachspezifischen
					Terminologie</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=94 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=57 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">Begründung und Auswahl
					einer der Problemstellung angemessene Untersuchungs&shy;methodik</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=94 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=57 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">schlüssige Umsetzung der
					Themenstellung und der Gliederungsstruktur in der <BR>inhaltlichen
					Bearbeitung, logisch konsistente Argumentation</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=94 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=57 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">Analyse und kritische
					Beurteilung vorgefundener Lösungsmuster in Theorie und Praxis</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=94 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=57 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">Entwicklung eigenständiger
					Ansätze bzw. Ideen mit Problemlösungspotenzial für die
					praktische Umsetzung</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=94 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=57 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">kritische Reflexion der
					eigenen Ergebnisse und Einschätzen zukünftig zu
					erwartender<BR>Entwicklungen</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=94 STYLE="border-top: 1px solid #808080; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=57 STYLE="border-top: 1px solid #808080; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=637 HEIGHT=165 VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in; margin-bottom: 0.04in">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Bemerkungen</B></FONT><FONT SIZE=2 STYLE="font-size: 9pt">:</FONT></P>
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR VALIGN=TOP>
			<TD WIDTH=342 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Maximale
				Punktzahl:		40</B></FONT></P>
			</TD>
			<TD COLSPAN=3 WIDTH=294 STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Erreichte
				Punktzahl:	</B></FONT></P>
			</TD>
		</TR>
	</TBODY>
</TABLE>
<P STYLE="margin-left: 0.3in; text-indent: -0.3in; margin-bottom: 0in; line-height: 100%">
<BR>
</P>
<P STYLE="margin-bottom: 0in; line-height: 100%"><BR>
</P>
<TABLE WIDTH=640 CELLPADDING=0 CELLSPACING=1>
	<COL WIDTH=342>
	<COL WIDTH=141>
	<COL WIDTH=95>
	<COL WIDTH=54>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=636 BGCOLOR="#5c6971" STYLE="border-top: 1px solid #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.03in; page-break-after: avoid">
				<FONT COLOR="#ffffff"><FONT SIZE=2><B>3. Quellenauswahl und
				Quellenauswertung</B></FONT></FONT></P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=17 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Prüfkriterien des
				Gutachters / Betreuers</B></FONT></P>
			</TD>
			<TD WIDTH=95 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Bewertungstendenz</B></FONT></P>
			</TD>
			<TD WIDTH=54 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>nicht<BR>relevant</B></FONT></P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=7 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.16in; margin-top: 0.04in; page-break-after: avoid">
				<BR>
				</P>
			</TD>
			<TD WIDTH=95 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
			<TD WIDTH=54 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=47 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">Berücksichtigung
					problemadäquater wissenschaftlicher Quellen (z. B.
					Monographien, Sammel&shy;bände, wissenschaftliche
					Zeitschriften, Working Paper usw.) in angemessenem Umfang</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=95 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=54 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">Berücksichtigung
					praxisnaher, z. B. firmen- oder branchenspezifischer
					Informationen</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=95 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=54 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=484 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.03in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">kritische Distanz bei der
					Quellenauswahl und Quellenauswertung</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=95 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=54 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=636 HEIGHT=193 VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in; margin-bottom: 0.04in">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Bemerkungen</B></FONT><FONT SIZE=2 STYLE="font-size: 9pt">:</FONT></P>
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR VALIGN=TOP>
			<TD WIDTH=342 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Maximale
				Punktzahl:		30</B></FONT></P>
			</TD>
			<TD COLSPAN=3 WIDTH=293 STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Erreichte
				Punktzahl:	</B></FONT></P>
			</TD>
		</TR>
	</TBODY>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%"><BR>
</P>
<TABLE WIDTH=640 CELLPADDING=0 CELLSPACING=1>
	<COL WIDTH=2340>
	<COL WIDTH=963>
	<COL WIDTH=662>
	<COL WIDTH=397>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=4365 BGCOLOR="#5c6971" STYLE="border-top: 1px solid #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.03in; page-break-after: avoid">
				<FONT COLOR="#ffffff"><FONT SIZE=2><B>4. Formale Aspekte</B></FONT></FONT></P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=3304 HEIGHT=17 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Prüfkriterien des
				Gutachters / Betreuers</B></FONT></P>
			</TD>
			<TD WIDTH=662 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in; page-break-after: avoid">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Bewertungstendenz</B></FONT></P>
			</TD>
			<TD WIDTH=397 STYLE="border-top: 2.25pt double #000000; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>nicht<BR>relevant</B></FONT></P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=3304 HEIGHT=7 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.16in; margin-top: 0.04in; page-break-after: avoid">
				<BR>
				</P>
			</TD>
			<TD WIDTH=662 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
			<TD WIDTH=397 BGCOLOR="#5c6971" STYLE="border-top: none; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
		<TR>
			<TD COLSPAN=2 WIDTH=3304 HEIGHT=33 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.04in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">korrekte äußere Form (z.
					B. Deckblatt, Selbstständigkeitserklärung, Druckbild)</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=662 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=397 STYLE="border-top: none; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=3304 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.04in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">formal korrektes Erstellen
					aller erforderlichen Verzeichnisse (Inhalts- und
					Quellenverzeichnis, ggf. Abbildungs- , Tabellen- und
					Abkürzungsverzeichnis sowie Anhang )</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=662 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=397 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=3304 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.04in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">korrekte Anwendung der
					Regeln der Rechtschreibung, Grammatik und Interpunktion,
					angemessener sprachlicher Stil</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=662 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=397 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=3304 HEIGHT=53 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.04in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">Einhalten der Regeln zum
					Umfang von Projektarbeiten (20 – 30 Seiten)
					bzw.<BR>Bachelor&#8209;Arbeiten (60 – 80 Seiten),
					<BR>Abweichungen sind nur mit Zustimmung des Betreuers möglich</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=662 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=397 STYLE="border-top: 1px solid #808080; border-bottom: 1px solid #808080; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=2 WIDTH=3304 HEIGHT=33 STYLE="border-top: 1px solid #808080; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<UL>
					<P STYLE="margin-right: 0.04in; margin-top: 0.04in; page-break-after: avoid">
					<FONT SIZE=2 STYLE="font-size: 9pt">exakte Kenntlichmachung
					aller fremder Quellen durch korrekte konsistente Zitiertechnik</FONT></P>
				</UL>
			</TD>
			<TD WIDTH=662 STYLE="border-top: 1px solid #808080; border-bottom: none; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P ALIGN=CENTER STYLE="margin-top: 0.03in">– – <FONT SIZE=2 STYLE="font-size: 9pt"><B>	
				– 		o	 + 		++</B></FONT></P>
			</TD>
			<TD WIDTH=397 STYLE="border-top: 1px solid #808080; border-bottom: none; border-left: 1px solid #000000; border-right: 1px solid #000000; padding: 0in">
				<P STYLE="margin-top: 0.03in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR>
			<TD COLSPAN=4 WIDTH=4365 HEIGHT=142 VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in; margin-bottom: 0.04in">
				<FONT SIZE=2 STYLE="font-size: 9pt"><B>Bemerkungen</B></FONT><FONT SIZE=2 STYLE="font-size: 9pt">:</FONT></P>
				<P STYLE="margin-top: 0.04in"><BR>
				</P>
			</TD>
		</TR>
	</TBODY>
	<TBODY>
		<TR VALIGN=TOP>
			<TD WIDTH=2340 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Maximale
				Punktzahl:		10</B></FONT></P>
			</TD>
			<TD COLSPAN=3 WIDTH=2024 STYLE="border: 1px solid #000000; padding: 0in">
				<P STYLE="margin-left: 0.04in; margin-top: 0.04in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Erreichte
				Punktzahl:	</B></FONT></P>
			</TD>
		</TR>
	</TBODY>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%"><BR>
</P>
<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0>
	<COL WIDTH=256*>
	<TR>
		<TD WIDTH=100% HEIGHT=200 VALIGN=TOP STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in; margin-bottom: 0.04in">
			<FONT SIZE=2 STYLE="font-size: 9pt"><B>Zusammenfassende
			Beurteilung:</B></FONT></P>
			<P STYLE="margin-left: 0.04in; margin-top: 0.04in">${SuperVisorOpinionText}</P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%"><BR>
</P>
<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0>
	<COL WIDTH=137*>
	<COL WIDTH=119*>
	<TR>
		<TD WIDTH=54% HEIGHT=48 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.08in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Von
			max. 100 Punkten wurden erreicht:	</B></FONT></P>
		</TD>
		<TD WIDTH=46% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.08in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Die
			Arbeit wird bewertet mit:	&lt;Grade&gt;</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=54% HEIGHT=59 STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.17in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Ort,
			Datum:		${Place}</B></FONT></P>
		</TD>
		<TD WIDTH=46% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-top: 0.17in"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Unterschrift:</B></FONT></P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%"><BR>
</P>
<P STYLE="margin-bottom: 0in; line-height: 100%"><FONT SIZE=2 STYLE="font-size: 9pt"><B>Bewertungshinweise:</B></FONT></P>
<P STYLE="margin-bottom: 0in; line-height: 100%"><FONT SIZE=1><B>Extreme
Mängel in einem der vier Bewertungsabschnitte führen in der Regel
zu einer Ablehnung der gesamten Arbeit (umfangreiche Begründung)!</B></FONT></P>
<P STYLE="margin-bottom: 0in; line-height: 100%"><FONT SIZE=1><B>Orientierungsraster
zur Notenfindung (zur Bestimmung der Dezimalnote im jeweiligen
Punkteintervall siehe die beigefügte Punkte-Noten-Skala)!</B></FONT></P>
<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=0>
	<COL WIDTH=64*>
	<COL WIDTH=60*>
	<COL WIDTH=131*>
	<TR>
		<TD WIDTH=25% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>1,0 bis 1,5	=	sehr gut</FONT></P>
		</TD>
		<TD WIDTH=24% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>100 bis 93 Punkte</FONT></P>
		</TD>
		<TD WIDTH=51% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>= eine hervorragende Leistung</FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=25% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>1,6 bis 2,5	=	gut</FONT></P>
		</TD>
		<TD WIDTH=24% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>92 bis 76 Punkte</FONT></P>
		</TD>
		<TD WIDTH=51% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>= eine erheblich über dem Durchschnitt liegende
			Leistung</FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=25% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>2,6 bis 3,5	=	befriedigend</FONT></P>
		</TD>
		<TD WIDTH=24% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>75 bis 59 Punkte</FONT></P>
		</TD>
		<TD WIDTH=51% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>= eine Leistung, die durchschnittlichen Anforderungen
			entspricht</FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=25% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>3,6 bis 4,0	=	ausreichend</FONT></P>
		</TD>
		<TD WIDTH=24% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>58 bis 50 Punkte</FONT></P>
		</TD>
		<TD WIDTH=51% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>= eine Leistung, die trotz ihrer Mängel noch den
			Anforderungen entspricht</FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=25% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>4,1 bis 5,0	=	nicht ausreichend</FONT></P>
		</TD>
		<TD WIDTH=24% STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: none; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>49 bis 25 Punkte / </FONT><FONT FACE="Symbol, serif"><FONT SIZE=1></FONT></FONT><FONT SIZE=1>
			25 Punkte 5,0</FONT></P>
		</TD>
		<TD WIDTH=51% STYLE="border: 1px solid #000000; padding: 0in">
			<P STYLE="margin-left: 0.04in; margin-right: 0.04in; margin-top: 0.01in">
			<FONT SIZE=1>= eine Leistung, die wegen erheblicher Mängel den
			Anforderungen nicht mehr genügt</FONT></P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%; page-break-before: always">
<BR>
</P>
<P ALIGN=CENTER STYLE="margin-bottom: 0in; line-height: 100%"><FONT SIZE=4 STYLE="font-size: 16pt"><B>Punkte-
und Notenskala</B></FONT></P>
<TABLE WIDTH=100% CELLPADDING=7 CELLSPACING=0>
	<COLGROUP>
		<COL WIDTH=37*>
	</COLGROUP>
	<COLGROUP>
		<COL WIDTH=37*>
	</COLGROUP>
	<COLGROUP>
		<COL WIDTH=37*>
	</COLGROUP>
	<COLGROUP>
		<COL WIDTH=37*>
		<COL WIDTH=37*>
		<COL WIDTH=37*>
		<COL WIDTH=34*>
	</COLGROUP>
	<TR>
		<TD ROWSPAN=8 WIDTH=14% VALIGN=TOP STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2><B>sehr
			gut</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>100</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="text-indent: -0.01in; margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,0</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD ROWSPAN=9 WIDTH=14% VALIGN=TOP STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2><B>ausreichend</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>58</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,6</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>99</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,1</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>57</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,7</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>98</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,1</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>56</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,7</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>97</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,2</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>55</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,8</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>96</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,3</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>54</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,8</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>95</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,3</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>53</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,9</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>94</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,4</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>52</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,9</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 2.50pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>93</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 2.50pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,5</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>51</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,0</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD ROWSPAN=17 WIDTH=14% VALIGN=TOP STYLE="border-top: 2.50pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2><B>gut</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 2.50pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>92</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 2.50pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,6</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 4.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>50</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 4.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,0</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>91</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,7</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD ROWSPAN=25 WIDTH=14% VALIGN=TOP STYLE="border-top: 4.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><FONT SIZE=2><B>nicht</B></FONT></P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2><B>ausreichend</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 4.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>49</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border-top: 4.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,1</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>90</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,7</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>48</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,1</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>89</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,8</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>47</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,2</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>88</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,8</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>46</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,2</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>87</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,9</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>45</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,3</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>86</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>1,9</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>44</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,3</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>85</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,0</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>43</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,3</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>84</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,1</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>42</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,4</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>83</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,1</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>41</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,4</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>82</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,2</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>40</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,5</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>81</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,2</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>39</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,5</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>80</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,3</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>38</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,5</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>79</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,3</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>37</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,6</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>78</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,4</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>36</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,6</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>77</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,4</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>35</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,6</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 2.50pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>76</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 2.50pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,5</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>34</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,7</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD ROWSPAN=17 WIDTH=14% VALIGN=TOP STYLE="border-top: 2.50pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in; margin-bottom: 0.03in"><BR><BR>
			</P>
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=2><B>befriedigend</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 2.50pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>75</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 2.50pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,6</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>33</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,7</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>74</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,7</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>32</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,7</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>73</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,7</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>31</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,8</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>72</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,8</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>30</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,8</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>71</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,8</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>29</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,8</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>70</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,9</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>28</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,9</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>69</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>2,9</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>27</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,9</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>68</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,0</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>26</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>4,9</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>67</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,1</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>25
			und weniger</B></FONT></P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: 1.00pt solid #000000; padding: 0in 0.08in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>5,0</B></FONT></P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>66</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,1</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: 1.00pt solid #000000; border-bottom: none; border-left: none; border-right: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: none; border-left: none; border-right: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: none; border-left: none; border-right: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>65</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,2</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>64</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,2</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>63</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,3</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>62</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,3</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>61</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,4</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>60</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,4</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
	<TR>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 2.50pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>59</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border-top: 1.00pt solid #000000; border-bottom: 2.50pt solid #000000; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><FONT SIZE=1 STYLE="font-size: 8pt"><B>3,5</B></FONT></P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border-top: none; border-bottom: none; border-left: 1.00pt solid #000000; border-right: none; padding-top: 0in; padding-bottom: 0in; padding-left: 0.08in; padding-right: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=TOP STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=14% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
		<TD WIDTH=13% VALIGN=BOTTOM STYLE="border: none; padding: 0in">
			<P ALIGN=CENTER STYLE="margin-top: 0.03in"><BR>
			</P>
		</TD>
	</TR>
</TABLE>
<P STYLE="margin-bottom: 0in; line-height: 100%"><BR>
</P>
</BODY>
</HTML>